//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularSkeleton.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AngularSkeleton.Common.Resources.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0} cannot be null..
        /// </summary>
        public static string Error_ArgumentCannotBeNull {
            get {
                return ResourceManager.GetString("Error_ArgumentCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument &apos;{0} cannot be null or empty..
        /// </summary>
        public static string Error_ArgumentCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Error_ArgumentCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity of type \&quot;{0}\&quot; in state \&quot;{1}\&quot; has the following validation errors:.
        /// </summary>
        public static string Error_EntityValidation {
            get {
                return ResourceManager.GetString("Error_EntityValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Property: \&quot;{0}\&quot;, Error: \&quot;{1}\&quot;.
        /// </summary>
        public static string Error_EntityValidation_Property {
            get {
                return ResourceManager.GetString("Error_EntityValidation_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred..
        /// </summary>
        public static string Error_Generic {
            get {
                return ResourceManager.GetString("Error_Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service endpoint application setting &apos;{0}&apos; has not been set in the *.config..
        /// </summary>
        public static string Error_Service_EndpointUndefined {
            get {
                return ResourceManager.GetString("Error_Service_EndpointUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find &apos;{0}&apos; with id: &apos;{1}&apos;.
        /// </summary>
        public static string Error_UnableToFindEntityWithId {
            get {
                return ResourceManager.GetString("Error_UnableToFindEntityWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize the database..
        /// </summary>
        public static string Error_UnableToInitDatabase {
            get {
                return ResourceManager.GetString("Error_UnableToInitDatabase", resourceCulture);
            }
        }
    }
}
